#!/bin/bash -e
#
# Copyright (c) 2018 SUSE LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

SCRIPT=$(basename ${0})
BASE_DIR=$(dirname "${0}")
PACKAGE_NAME="containment-rpm-pxe"
FOR_OBS_DIR="${BASE_DIR}/for_obs/"
REGEX_VERSION="^Version:\s*([^\s]*)$"

if [ -d ${FOR_OBS_DIR} ]; then
  echo "ERROR: Directory ${FOR_OBS_DIR} already exists!"
  exit 1
fi

while read p; do
  if [[ ${p} =~ ${REGEX_VERSION} ]]; then
    PACKAGE_VERSION="${BASH_REMATCH[1]}"
    break
  fi
done <${BASE_DIR}/${PACKAGE_NAME}.spec

SOURCES_DIR="${FOR_OBS_DIR}/${PACKAGE_NAME}-${PACKAGE_VERSION}"
mkdir -p ${SOURCES_DIR}
cp ${BASE_DIR}/${PACKAGE_NAME}.* ${FOR_OBS_DIR}
cp ${BASE_DIR}/image.spec.in ${SOURCES_DIR}
cp ${BASE_DIR}/kiwi_post_run ${SOURCES_DIR}
cd ${FOR_OBS_DIR}
tar -czf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz ${PACKAGE_NAME}-${PACKAGE_VERSION}
rm -rf ${PACKAGE_NAME}-${PACKAGE_VERSION}
echo "INFO: Please upload the content of directory ${FOR_OBS_DIR} to your OBS package"
